version: '2'

services:
  web:
    build: ./build/magento/
    ports:
      - "80:80"
    links:
      - mysql
    env_file:
      - env
    depends_on: 
      - mysql
    volumes:
     - ./Code:/var/www/htdocs
  mysql:
    build: ./build/mysql/
    env_file:
      - env
    volumes:
     - ./SqlData:/var/lib/mysql